[package]
name = "ms-executor"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = {version = "1.2.2", features = ["v4"]}
futures = "0.3"
protos = { path = "../protos"}
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
tonic = "0.8.3"