[package]
name = "protos"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"
resolver = "2"

[dependencies]
tonic = "0.8.3"
prost = "0.11.5"
[build-dependencies]
tonic-build = "0.8.4"