[package]
name = "protos"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"
resolver = "2"

[dependencies]
tonic = "0.12.0"
prost = "0.13.1"
[build-dependencies]
tonic-build = "0.12.0"