[package]
name = "ms-worker"
version = "0.1.0"
edition = "2021"

[dependencies]
mimalloc = { version = "*", default-features = false }
protos = { path = "../protos"}
tokio = { version = "1.38.0", features = ["full"] }
tonic = "0.12.0"

